# Generated by Django 4.0.1 on 2022-05-31 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='favorits',
            field=models.ManyToManyField(blank=True, related_name='favorits', to=settings.AUTH_USER_MODEL),
        ),
    ]
